name: Build Images
#
on:
  repository_dispatch:
    types: ["Dispatched jobs"]
  push:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: 'Release'
        options:
        - nightly
        - stable
      board:
        description: 'Board'
        required: false
        default: ''
      version:
        description: 'Version'
        required: false
        default: ''


jobs:

  Prepare:
    name: "Prepare"
    if: ${{ github.repository_owner == 'armbian-alpha' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.releases.outputs.version}}
    steps:

      - name: "Cancel active workflow"
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Keep only 32 nightly releases"
        uses: Vucko130/delete-older-releases@v0.2.2
        with:
          keep_latest: 32
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Purge action workflow logs"
        uses: igorjs/gh-actions-clean-workflow@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days_old: 10

  Version:
    name: "Generate version"
    needs: Prepare
    if: ${{ github.repository_owner == 'armbian-alpha' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.releases.outputs.version}}
    steps:
      - id: node_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: armbian
          repo: os
          excludes: draft

      - name: "Show"
        run: echo ${{ steps.node_release.outputs.release }}

      - name: "Store version"
        id: releases
        run: |

          echo "version=${{ steps.node_release.outputs.release }}" >> $GITHUB_OUTPUT
          
      - uses: ncipollo/release-action@v1
        if: ${{ steps.node_release.outputs.release != '' }}
        with:
          tag: ${{ steps.node_release.outputs.release }}
          name: "${{ steps.node_release.outputs.release }}"
          omitBody: "true"
          prerelease: "true"
          allowUpdates: true
          removeArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
        
  Cluster_1:

    needs: Version
    name: "Cluster 1/6"
    if: ${{ success() && github.repository_owner == 'armbian-alpha' }}
    uses: armbian/scripts/.github/workflows/build-images.yml@main

    with:

      config: "${{ github.event.inputs.config || 'default.conf' }}"
      release: "${{ github.event.inputs.release || 'nightly' }}"
      board: '${{ github.event.inputs.board }}'
      part: 1
      of: 6
      version: "${{ needs.Version.outputs.version }}"

    secrets:
      ACCESS_TOKEN:  ${{ secrets.GITHUB_TOKEN }} # ${{ secrets.ACCESS_TOKEN }}
      SSH_KEY_TORRENTS: ${{ secrets.KEY_TORRENTS }}
      KNOWN_HOSTS_UPLOAD: ${{ secrets.KNOWN_HOSTS_UPLOAD }}
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
